- name: catalogue setup
  hosts: catalogue
  become: true
  tasks:
  - name: disable nodejs module
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: create user
    ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user"
      shell: /sbin/nologin
      home: /app
      system: true

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: remove catalogue file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy catalogue services
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongodb repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh -y
      state: present
  
  - name: connnect to mongodb catalogue
    ansible.builtin.command: mongosh mongodb.daws86s.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    register: catalogue_output

  - name: load products into mongodb
    ansible.builtin.shell: mongosh --host mongodb.daws86s.fun </app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: catalogue
      enabled: true
      state: started
      daemon_reload: true

  

