- name: mysql setup
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present


  - name: enable and start
    ansible.builtin.service:
      name: mysqld
      enabled: true
      state: started

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1